<script lang="ts">
  import buttonView from "./n-icons/button-view.svelte";
  import detailView from "./n-icons/detail-view.svelte";
  // import RadioButtonChecked24 from "carbon-icons-svelte/lib/RadioButtonChecked24";
  // import Shuffle24 from "carbon-icons-svelte/lib/Shuffle24";
  // import RadioButton24 from "carbon-icons-svelte/lib/RadioButton24";

  // Hero Icons
  import {
    ArrowCircleUp,
    ArrowLeft,
    Exclamation,
    ArrowUp,
    ArrowsExpand,
    Calendar,
    ChartBar,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ClipboardCopy,
    Clock,
    Cog,
    DotsHorizontal,
    Download,
    FolderAdd,
    Link,
    LocationMarker,
    Menu,
    MinusCircle,
    PaperAirplane,
    Pencil,
    Plus,
    PlusCircle,
    PresentationChartLine,
    Refresh,
    Search,
    Share,
    SortAscending,
    Star,
    SwitchHorizontal,
    Trash,
    User,
    UserAdd,
    UserGroup,
    ViewBoards,
    ViewGrid,
    Home,
    X,
    XCircle,
    DotsVertical,
    ChartPie,
    DotsCircleHorizontal,
    ViewList,
    Eye,
    EyeOff,
    Map,
    Annotation,
    Beaker,
    Bell,
    LockClosed,
    ArrowRight,
    Cake,
    LightBulb,
    PencilAlt,
    BookOpen,
    Upload,
    Library,
    Chip,
    Adjustments,
    Collection,
    SortDescending,
    ChartSquareBar,
    UserCircle,
    Duplicate,
    Play,
    Stop,
  } from "svelte-hero-icons";

  export let name = "add";
  export let style:string | undefined = undefined;
  export let className = "";
  export let title = "";
  export let size:number = 24

  export let icon:any = undefined;

  const icons = {
    add: Plus,
    chip: Chip,
    adjust: Adjustments,
    library: Library,
    alert: Exclamation,
    bell: Bell,
    tab: Collection,
    addFolder: FolderAdd,
    addTab: FolderAdd,
    duplicate: Duplicate,
    sortUp: SortAscending,
    sortDown: SortDescending,
    switch: SwitchHorizontal,
    lock: LockClosed,
    annotation: Annotation,
    expand: ArrowsExpand,
    beaker: Beaker,
    addOutline: PlusCircle,
    arrowBack: ArrowLeft,
    arrowRight: ArrowRight,
    upload: Upload,
    arrowUp: ArrowUp,
    arrowsLeftRight: SwitchHorizontal,
    calendar: Calendar,
    chart: ChartBar,
    chart2: ChartSquareBar,
    play: Play,
    stop: Stop,
    cake: Cake,
    checkmark: Check,
    checkmarkFilled: CheckCircle,
    checkmarkOutline: CheckCircle,
    chevronDown: ChevronDown,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    close: X,
    closeFilled: XCircle,
    closeOutline: XCircle,
    copy: ClipboardCopy,
    home: Home,
    dashboard: ViewBoards,
    delete: Trash,
    download: Download,
    edit: Pencil,
    pieChart: ChartPie,
    grid: ViewGrid,
    link: Link,
    list: ViewList,
    bulb: LightBulb,
    map: Map,
    menu: Menu,
    more: DotsHorizontal,
    moreOutline: DotsCircleHorizontal,
    moreVertical: DotsVertical,
    newTab: FolderAdd,
    people: UserGroup,
    pin: LocationMarker,
    radio: PlusCircle,
    userCircle: UserCircle,
    radioFilled: CheckCircle,
    refresh: Refresh,
    remove: MinusCircle,
    report: PresentationChartLine,
    search: Search,
    sendFilled: ArrowCircleUp,
    airplane: PaperAirplane,
    settings: Cog,
    share: Share,
    shuffle: Refresh,
    sort: SortAscending,
    star: Star,
    time: Clock,
    tracker: ViewGrid,
    userAdd: UserAdd,
    user: User,
    buttonView: buttonView,
    detailView: detailView,
    eye: Eye,
    eyeOff: EyeOff,
    compose: PencilAlt,
    book: BookOpen,
  };
</script>

<style>
  .n-icon {
    display: inline-flex;
  }
</style>

{#if icons[name] || icon}
  <span class="n-icon n-icon-{name} {className}" {style} aria-label={title}>
    <svelte:component this={icon || icons[name]} size={`${size || 24}`} />
  </span>
{/if}
